In [1]:
# Dependencies
import pandas as pd
import numpy as np
import requests
import json

# Yelp API Key
gkey = 'fxuoEjmZHd5kA1x20u4z2waSsXfTm49pWr2F6ac-htERJ0haCqXH949tlmDYt9lhy4MC6nBJjt2llMwhQJfxbwX69QlFkI221WkMDZTn7NMQBaXRrWGBFzCrg4-9XXYx'

In [2]:
from etl_clean_ip import zip_list

/Users/monicamalarcon/Dropbox/School/UM_Bootcamp/Work_Bootcamp/13 - ETL-Project/ETL-project/ETL-Project/Data/etl_clean_ip.py:231: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  top30_disparity['zip_code'] = top30_disparity['zip_code'].astype(int)
/Users/monicamalarcon/Dropbox/School/UM_Bootcamp/Work_Bootcamp/13 - ETL-Project/ETL-project/ETL-Project/Data/etl_clean_ip.py:232: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  top30_disparity['Avg_income'] = top30_disparity['Avg_income'].round(3)

In [3]:
#set up base url
# base url
base_url = "https://api.yelp.com/v3/businesses/search"

# set up api_key dictionary
headers = {
        'Authorization': 'Bearer %s' % gkey,
    }

# set up a parameters dictionary
def s_params(target_loc,target_key,target_type):
    params = {
    "location": target_loc,
    "term": target_key,
    "categories": target_type,
}
    return params

# run a request using our params dictionary
def s_query(base_url,headers,params):
    response = requests.request('GET', base_url, headers=headers, params=params).json()
    return response

In [4]:
# Import zip list
zip_list 

#cities_pd.shape[0] #use .shape[0] to count the number of rows

[33142,
 33127,
 33147,
 33125,
 33136,
 33012,
 33167,
 33126,
 33150,
 33032,
 33130,
 33162,
 33034,
 33055,
 33056,
 33174,
 33172,
 33033,
 33168,
 33190,
 33169,
 33181,
 33030,
 33014,
 33193,
 33016,
 33161,
 33184,
 33194,
 33035]

In [10]:
# yelp function
def get_restaurants(loc):
    
    #these are the additional params
    add_params = {"limit" : 5, "sort_by": "best_match"}

    #these are the original params
    params = s_params(loc,"restaurants","restaurants, All")

    #add additional params to our params from before
    s1_params = {**params,**add_params}

    s1_results = s_query(base_url,headers,s1_params)
    
#     for result in s1_results:
    try:
        name = s1_results["businesses"][0]["name"]
        address1 = s1_results["businesses"][0]["location"]["address1"]
        city = s1_results["businesses"][0]["location"]["city"]
        state = s1_results["businesses"][0]["location"]["state"]
        zipcode = s1_results["businesses"][0]["location"]["zip_code"]
        rating = s1_results["businesses"][0]["rating"]
        price = s1_results["businesses"][0]["price"]
        restaurants = [name,address1,city,zipcode,rating,price] 
        print(restaurants)
    except KeyError:
        print(f'Key not found. Missing data.')
        restaurants = ["NaN","NaN","NaN","NaN","NaN","NaN"]

    return restaurants

In [11]:
# Loop through the zips list and run a search for each zip
names = []
streets = []
cities = []
zipcs = []
ratings = []
prices = []


print("wait...retrieving data")


for zips in zip_list:
    loc = zips
    output = get_restaurants(loc)
    names.append(output[0])
    streets.append(output[1])
    cities.append(output[2])
    zipcs.append(output[3])
    ratings.append(output[4])
    prices.append(output[5])
        
# # make exception for key errors        
#     except (KeyError, IndexError):
#         search = ["NaN","NaN","NaN","NaN","NaN","NaN"]
#     names.append(search[0])
#     streets.append(search[1])
#     cities.append(search[2])
#     zipcs.append(search[3])
#     ratings.append(search[4])
#     prices.append(search[5])
    
    
print("done!")

wait...retrieving data
['Hometown Bar-B-Que', '1200 NW 22nd St', 'Miami', '33142', 4.5, '$$']
['KYU', '251 NW 25th St', 'Miami', '33127', 4.5, '$$$']
['Sins Gastrobar', '9835 NE 2nd Ave', 'Miami Shores', '33138', 4.0, '$$']
["Old's Havana Cuban Bar & Cocina", '1442 SW 8th St', 'Miami', '33135', 4.5, '$$']
['Bunbury', '55 NE 14th St', 'Miami', '33132', 4.5, '$$']
Key not found. Missing data.
['Sins Gastrobar', '9835 NE 2nd Ave', 'Miami Shores', '33138', 4.0, '$$']
['Fratellino', '264 Miracle Mile', 'Coral Gables', '33134', 5.0, '$$']
['Sins Gastrobar', '9835 NE 2nd Ave', 'Miami Shores', '33138', 4.0, '$$']
Key not found. Missing data.
['The Wharf Miami', '114 SW North River Dr', 'Miami', '33130', 4.0, '$$']
['Korean Kitchen', '1661 NE 163rd St', 'North Miami Beach', '33162', 4.5, '$$']
['Blackwater Siren', '107690 Overseas Hwy', 'Key Largo', '33037', 4.5, '$$']
['World Famous', '19401 NW 27th Ave', 'Miami Gardens', '33056', 4.0, '$$']
['World Famous', '19401 NW 27th Ave', 'Miami Gardens', '33056', 4.0, '$$']
['Cajun Boil', '10162 W Flagler St', 'Miami', '33174', 4.5, '$$']
['Bocas House- Doral', '10200 NW 25th St', 'Doral', '33172', 4.0, '$$']
['Yardie Spice', '225 S Krome Ave', 'Homestead', '33030', 5.0, '$$']
['Sins Gastrobar', '9835 NE 2nd Ave', 'Miami Shores', '33138', 4.0, '$$']
Key not found. Missing data.
['World Famous House of Mac', '13521 Biscayne Blvd', 'North Miami Beach', '33181', 4.5, '$$']
['World Famous House of Mac', '13521 Biscayne Blvd', 'North Miami Beach', '33181', 4.5, '$$']
['Yardie Spice', '225 S Krome Ave', 'Homestead', '33030', 5.0, '$$']
['107 Taste - Miami Lakes', '6705 Main St', 'Miami Lakes', '33014', 4.5, '$$']
['KOW Restaurant', '14429 SW 42nd St', 'Miami', '33175', 4.5, '$$']
Key not found. Missing data.
['World Famous House of Mac', '13521 Biscayne Blvd', 'North Miami Beach', '33181', 4.5, '$$']
['KOW Restaurant', '14429 SW 42nd St', 'Miami', '33175', 4.5, '$$']
['KOW Restaurant', '14429 SW 42nd St', 'Miami', '33175', 4.5, '$$']
['Yardie Spice', '225 S Krome Ave', 'Homestead', '33030', 5.0, '$$']
done!

In [12]:
# Add columns for lat, lng, airport name, airport address, airport rating
restaurants_df = pd.DataFrame({"Name": names,"Location": streets, "City": cities, "Zipcode":zipcs, "Rating": ratings,"Price": prices})

In [13]:
restaurants_df.dropna(how="any", inplace=True)
restaurants_df

,Name,Location,City,Zipcode,Rating,Price
0,Hometown Bar-B-Que,1200 NW 22nd St,Miami,33142,4.5,$$
1,KYU,251 NW 25th St,Miami,33127,4.5,$$$
2,Sins Gastrobar,9835 NE 2nd Ave,Miami Shores,33138,4,$$
3,Old's Havana Cuban Bar & Cocina,1442 SW 8th St,Miami,33135,4.5,$$
4,Bunbury,55 NE 14th St,Miami,33132,4.5,$$
5,NaN,NaN,NaN,NaN,NaN,NaN
6,Sins Gastrobar,9835 NE 2nd Ave,Miami Shores,33138,4,$$
7,Fratellino,264 Miracle Mile,Coral Gables,33134,5,$$
8,Sins Gastrobar,9835 NE 2nd Ave,Miami Shores,33138,4,$$
9,NaN,NaN,NaN,NaN,NaN,NaN
10,The Wharf Miami,114 SW North River Dr,Miami,33130,4,$$
11,Korean Kitchen,1661 NE 163rd St,North Miami Beach,33162,4.5,$$
12,Blackwater Siren,107690 Overseas Hwy,Key Largo,33037,4.5,$$
13,World Famous,19401 NW 27th Ave,Miami Gardens,33056,4,$$
14,World Famous,19401 NW 27th Ave,Miami Gardens,33056,4,$$
15,Cajun Boil,10162 W Flagler St,Miami,33174,4.5,$$
16,Bocas House- Doral,10200 NW 25th St,Doral,33172,4,$$
17,Yardie Spice,225 S Krome Ave,Homestead,33030,5,$$
18,Sins Gastrobar,9835 NE 2nd Ave,Miami Shores,33138,4,$$
19,NaN,NaN,NaN,NaN,NaN,NaN
20,World Famous House of Mac,13521 Biscayne Blvd,North Miami Beach,33181,4.5,$$
21,World Famous House of Mac,13521 Biscayne Blvd,North Miami Beach,33181,4.5,$$
22,Yardie Spice,225 S Krome Ave,Homestead,33030,5,$$
23,107 Taste - Miami Lakes,6705 Main St,Miami Lakes,33014,4.5,$$
24,KOW Restaurant,14429 SW 42nd St,Miami,33175,4.5,$$
25,NaN,NaN,NaN,NaN,NaN,NaN
26,World Famous House of Mac,13521 Biscayne Blvd,North Miami Beach,33181,4.5,$$
27,KOW Restaurant,14429 SW 42nd St,Miami,33175,4.5,$$
28,KOW Restaurant,14429 SW 42nd St,Miami,33175,4.5,$$
29,Yardie Spice,225 S Krome Ave,Homestead,33030,5,$$

In [9]:
# # Save Data to csv
# cities_pd.to_csv("Airport_Output.csv")

# # Visualize to confirm airport data appears
# cities_pd.head(10)