In [2]:
import pandas as pd

In [3]:
file = './source-files/Miami-Dade_ZipCodeTabulatedArea.csv'
ZCTA = pd.read_csv(file)

In [4]:
ZCTA.head()

,OBJECTID,PZIPCODEID,ZIP,ZIPCODE,Shape__Area,Shape__Length,GlobalID
0,1,33035,33035,33035,2.917428e+08,85419.892940,ff9a785d-0f71-4541-9951-9c8d439b42c6
1,2,33010,33010,33010,1.317051e+07,19851.540060,ff56a32a-b713-4acf-ba60-e7a24daadadc
2,3,33154,33154,33154,1.003669e+07,15339.770690,e0eb98ac-facd-48b0-8a7e-7e4dfd1afbf0
3,4,33037,33037,33037,5.470778e+05,3500.649627,7a7e3954-a67a-4dac-940f-89d62d9aa090
4,5,33116,33116,33116,3.025113e+04,802.531871,8947a873-8ae0-4d30-98a1-e36163e1673c

In [5]:
miami_zips = pd.DataFrame(ZCTA[["ZIPCODE"]])

In [6]:
to_file = miami_zips.to_csv("MDC_zips.csv", sep=",", index=True)

In [7]:
#THIS DATA IS FROM 2016... TOO OLD
file2 = './source-files/ACSST5Y2018.S1902_data_with_overlays_2020-01-11T105425.csv'
income = pd.read_csv(file2)

income.head(50)

,GEO_ID,NAME,S1902_C01_001E,S1902_C01_001M,S1902_C02_001E,S1902_C02_001M,S1902_C03_001E,S1902_C03_001M,S1902_C01_002E,S1902_C01_002M,...,S1902_C02_027E,S1902_C02_027M,S1902_C03_027E,S1902_C03_027M,S1902_C01_028E,S1902_C01_028M,S1902_C02_028E,S1902_C02_028M,S1902_C03_028E,S1902_C03_028M
0,id,Geographic Area Name,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number MOE!!HOUSEHOLD INCOME!...,Estimate!!Percent Distribution!!HOUSEHOLD INCO...,Margin of Error!!Percent Distribution MOE!!HOU...,Estimate!!Mean income (dollars)!!HOUSEHOLD INC...,Margin of Error!!Mean income (dollars) MOE!!HO...,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number MOE!!HOUSEHOLD INCOME!...,...,Estimate!!Percent Distribution!!PER CAPITA INC...,Margin of Error!!Percent Distribution MOE!!PER...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars) MOE!!PE...,Estimate!!Number!!PER CAPITA INCOME BY RACE AN...,Margin of Error!!Number MOE!!PER CAPITA INCOME...,Estimate!!Percent Distribution!!PER CAPITA INC...,Margin of Error!!Percent Distribution MOE!!PER...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars) MOE!!PE...
1,1400000US12086000107,"Census Tract 1.07, Miami-Dade County, Florida",1346,204,1346,204,80065,14583,1001,191,...,50.3,9.1,32096,4768,1224,280,45.6,8.9,52191,12375
2,1400000US12086000109,"Census Tract 1.09, Miami-Dade County, Florida",1639,157,1639,157,51107,10049,1304,177,...,62.8,7.7,18077,5810,740,185,17.1,4.5,28936,9580
3,1400000US12086000113,"Census Tract 1.13, Miami-Dade County, Florida",3632,425,3632,425,96580,16736,2664,422,...,40.8,8.2,44731,8140,3803,656,54.5,8.1,57610,11573
4,1400000US12086000115,"Census Tract 1.15, Miami-Dade County, Florida",1089,175,1089,175,155974,43076,919,183,...,47.6,8.9,38627,15700,1435,292,49.9,8.8,83085,29849
5,1400000US12086000118,"Census Tract 1.18, Miami-Dade County, Florida",487,103,487,103,292064,98591,330,86,...,26.5,8.8,182388,105293,762,207,68.9,9.4,113534,48894
6,1400000US12086000119,"Census Tract 1.19, Miami-Dade County, Florida",2090,280,2090,280,92746,28018,1273,293,...,37.1,8.2,37718,16884,2662,633,59.2,8.4,50695,24137
7,1400000US12086000120,"Census Tract 1.20, Miami-Dade County, Florida",1773,135,1773,135,121055,19630,1435,120,...,52.4,5.7,46877,8988,1769,247,42.0,5.3,58802,16532
8,1400000US12086000121,"Census Tract 1.21, Miami-Dade County, Florida",612,83,612,83,145378,40463,342,64,...,24.4,10.2,36999,22089,931,216,70.0,10.2,74038,25070
9,1400000US12086000122,"Census Tract 1.22, Miami-Dade County, Florida",2125,274,2125,274,96652,17361,1326,281,...,33.2,9.3,30230,11231,2505,580,64.6,9.5,67666,16714
10,1400000US12086000123,"Census Tract 1.23, Miami-Dade County, Florida",1861,221,1861,221,109064,25807,1204,205,...,30.1,6.1,37256,12992,2832,385,62.4,6.0,54025,15295
11,1400000US12086000124,"Census Tract 1.24, Miami-Dade County, Florida",981,101,981,101,43910,7558,808,96,...,41.9,7.5,18627,4335,418,145,14.2,4.9,19268,10086
12,1400000US12086000125,"Census Tract 1.25, Miami-Dade County, Florida",1816,246,1816,246,67888,13898,1317,224,...,45.5,11.1,35632,13705,1585,394,45.7,9.5,38611,7515
13,1400000US12086000126,"Census Tract 1.26, Miami-Dade County, Florida",1128,155,1128,155,70335,27791,533,117,...,23.2,8.1,22171,7784,1392,271,69.9,9.4,44161,22648
14,1400000US12086000127,"Census Tract 1.27, Miami-Dade County, Florida",1378,149,1378,149,79512,17408,963,143,...,41.0,8.6,43160,15200,1655,336,55.4,9.2,34762,8019
15,1400000US12086000128,"Census Tract 1.28, Miami-Dade County, Florida",1230,119,1230,119,72816,12452,1060,131,...,60.5,8.1,35619,8672,864,190,33.3,7.2,37979,7877
16,1400000US12086000129,"Census Tract 1.29, Miami-Dade County, Florida",1114,157,1114,157,229358,52430,598,159,...,29.5,9.1,120925,32296,1520,436,67.4,9.7,119308,28779
17,1400000US12086000130,"Census Tract 1.30, Miami-Dade County, Florida",1161,195,1161,195,111400,29350,766,148,...,28.5,9.1,51089,14660,1431,311,67.4,9.4,65928,20938
18,1400000US12086000131,"Census Tract 1.31, Miami-Dade County, Florida",1197,180,1197,180,130298,35260,1047,191,...,52.5,9.1,63643,32989,1284,348,43.2,8.4,51940,12983
19,1400000US12086000132,"Census Tract 1.32, Miami-Dade County, Florida",3417,404,3417,404,61284,9962,1872,352,...,47.1,8.7,38538,9144,2570,571,44.0,8.5,38683,9533
20,1400000US12086000133,"Census Tract 1.33, Miami-Dade County, Florida",2817,313,2817,313,169910,25587,2164,264,...,35.5,5.7,70484,19799,4147,574,61.4,5.8,72744,14953
21,1400000US12086000134,"Census Tract 1.34, Miami-Dade County, Florida",1714,173,1714,173,53815,9239,1206,194,...,54.9,8.5,27273,6674,1270,273,38.7,7.5,35080,8008
22,1400000US12086000140,"Census Tract 1.40, Miami-Dade County, Florida",1829,168,1829,168,58363,6879,1575,189,...,66.7,6.4,26009,4741,981,302,24.5,6.8,28756,8320
23,1400000US12086000202,"Census Tract 2.02, Miami-Dade County, Florida",2177,179,2177,179,49354,7335,1807,191,...,46.3,8.8,15343,3525,1640,421,24.0,6.6,26987,6028
24,1400000US12086000204,"Census Tract 2.04, Miami-Dade County, Florida",1137,85,1137,85,60359,6137,1026,99,...,22.3,3.9,18362,3609,229,147,4.8,3.1,25976,8152
25,1400000US12086000206,"Census Tract 2.06, Miami-Dade County, Florida",1629,82,1629,82,47119,4967,1376,109,...,19.7,4.5,14019,3452,641,208,9.5,2.9,25313,7919
26,1400000US12086000209,"Census Tract 2.09, Miami-Dade County, Florida",1979,113,1979,113,38178,5342,1588,163,...,16.4,4.4,18919,6530,522,183,7.0,2.5,18968,10354
27,1400000US12086000211,"Census Tract 2.11, Miami-Dade County, Florida",977,66,977,66,59639,5620,862,70,...,52.5,6.6,20831,4507,611,169,21.2,6.0,28516,5128
28,1400000US12086000212,"Census Tract 2.12, Miami-Dade County, Florida",1767,112,1767,112,47433,12334,1516,144,...,42.7,5.5,18909,4454,324,121,6.7,2.5,31816,18570
29,1400000US12086000213,"Census Tract 2.13, Miami-Dade County, Florida",1383,112,1383,112,57180,7909,1127,119,...,15.8,5.3,20374,4785,1640,391,31.9,7.7,20593,4575
30,1400000US12086000214,"Census Tract 2.14, Miami-Dade County, Florida",2147,170,2147,170,65696,14936,1840,159,...,37.8,6.7,22263,9363,2035,642,29.3,8.0,17917,5418
31,1400000US12086000215,"Census Tract 2.15, Miami-Dade County, Florida",1166,92,1166,92,50404,6119,960,100,...,17.4,7.3,21128,5685,217,177,4.8,4.1,25006,13816
32,1400000US12086000216,"Census Tract 2.16, Miami-Dade County, Florida",1031,73,1031,73,63309,7332,924,88,...,21.9,6.9,17661,5002,56,40,1.2,0.8,22077,15826
33,1400000US12086000217,"Census Tract 2.17, Miami-Dade County, Florida",1566,83,1566,83,50331,5477,1308,100,...,16.0,4.3,18478,5563,297,152,4.4,2.3,22788,11100
34,1400000US12086000218,"Census Tract 2.18, Miami-Dade County, Florida",896,72,896,72,49061,5061,834,76,...,17.2,5.8,20078,4934,130,73,3.5,2.0,33322,16231
35,1400000US12086000219,"Census Tract 2.19, Miami-Dade County, Florida",1625,103,1625,103,43205,11526,1380,124,...,26.3,7.4,26116,13952,474,172,9.3,3.4,22288,7946
36,1400000US12086000220,"Census Tract 2.20, Miami-Dade County, Florida",1398,106,1398,106,46573,4176,1229,128,...,30.4,7.2,15640,2339,266,114,5.2,2.4,31408,10131
37,1400000US12086000301,"Census Tract 3.01, Miami-Dade County, Florida",1957,165,1957,165,57375,9123,1644,223,...,17.7,4.7,20627,8555,1000,438,12.6,4.7,17180,8111
38,1400000US12086000302,"Census Tract 3.02, Miami-Dade County, Florida",652,43,652,43,68741,9604,568,60,...,38.8,10.9,18285,2635,198,117,7.5,4.4,20296,12471
39,1400000US12086000305,"Census Tract 3.05, Miami-Dade County, Florida",2410,129,2410,129,45819,5442,2044,174,...,13.7,4.2,17423,4104,380,168,4.5,2.0,35604,17930
40,1400000US12086000306,"Census Tract 3.06, Miami-Dade County, Florida",1609,105,1609,105,48451,6883,1303,123,...,21.4,5.4,23019,5724,425,160,8.0,2.9,33890,17424
41,1400000US12086000307,"Census Tract 3.07, Miami-Dade County, Florida",1143,81,1143,81,70376,16472,926,98,...,26.7,5.4,15158,3220,216,111,4.5,2.3,33224,6953
42,1400000US12086000308,"Census Tract 3.08, Miami-Dade County, Florida",1271,92,1271,92,67331,6782,1092,96,...,21.7,5.3,20588,6378,408,108,7.2,1.9,41452,13424
43,1400000US12086000402,"Census Tract 4.02, Miami-Dade County, Florida",1131,53,1131,53,43050,12503,729,110,...,12.4,5.8,13183,5388,141,134,4.0,3.7,2460,1712
44,1400000US12086000403,"Census Tract 4.03, Miami-Dade County, Florida",2352,231,2352,231,35232,5747,1429,265,...,19.4,6.4,12684,2682,56,56,0.8,0.8,10039,14148
45,1400000US12086000404,"Census Tract 4.04, Miami-Dade County, Florida",2126,182,2126,182,51262,10973,1761,229,...,34.1,7.4,14878,2996,284,266,4.0,3.8,28020,15951
46,1400000US12086000405,"Census Tract 4.05, Miami-Dade County, Florida",1112,72,1112,72,54854,6437,889,119,...,24.6,6.5,18862,4763,140,85,3.0,1.8,18612,11676
47,1400000US12086000408,"Census Tract 4.08, Miami-Dade County, Florida",1592,90,1592,90,38277,5397,1116,129,...,30.5,6.0,14287,3141,110,65,2.2,1.3,11401,4137
48,1400000US12086000409,"Census Tract 4.09, Miami-Dade County, Florida",1221,74,1221,74,53500,7386,1033,89,...,25.0,9.3,16315,3619,11,15,0.2,0.3,N,N
49,1400000US12086000410,"Census Tract 4.10, Miami-Dade County, Florida",1082,86,1082,86,52525,8928,865,109,...,29.1,5.0,15370,3187,117,142,2.7,3.3,8694,3930